- name: Test connectivity to backend servers
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Ping test
      ansible.builtin.ping:

    - name: Install
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop:
      - mysql
      - postfix
