- name: Test connectivity to backend servers
  hosts: all
  gather_facts: false

  tasks:
    - name: Ping test
      ansible.builtin.ping:

    - name: Install
      ansible.builtin.dnf:
        name: mysql
        state: latest
